# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1db1ac4dc78b10b23b8b3b4d5508b71a424f9628f6bb332e5c283ededfba8674063b4e79880d31f21820be1a66f77fd1f4e51e9d16d68827510d994774c9876a

test:
  secret_key_base: 38de0a2d815dfe87047e4c05ea277bf46c986103e087031133c4242348c2ef6554d8a115b689693ab967b142f6ec8457ea5a572c122c90209e8987afcd13a72b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
